# Generated by Django 3.1.7 on 2021-06-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_no', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=25)),
                ('phno', models.CharField(max_length=10)),
                ('balance', models.IntegerField()),
            ],
        ),
    ]
