# Generated by Django 3.1.7 on 2021-06-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_account_no', models.CharField(max_length=10)),
                ('sender_name', models.CharField(max_length=25)),
                ('receiver_account_no', models.CharField(max_length=10)),
                ('receiver_name', models.CharField(max_length=25)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
