# Generated by Django 3.1.7 on 2021-06-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0002_transactions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='receiver_name',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='sender_name',
        ),
    ]
