# Generated by Django 3.1.7 on 2021-06-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_auto_20210603_1803'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='receiver_account_no',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='transactions',
            old_name='sender_account_no',
            new_name='sender',
        ),
    ]
